# Generated by Django 5.2.17 on 2026-09-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='options',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
