# Generated by Django 5.2.17 on 2026-10-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_job_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='tool',
            field=models.CharField(choices=[('merge', 'Merge PDF'), ('split', 'Split PDF'), ('compress', 'Compress PDF'), ('rotate', 'Rotate PDF'), ('pdf-to-jpg', 'PDF to JPG'), ('jpg-to-pdf', 'JPG to PDF'), ('protect', 'Protect PDF'), ('unlock', 'Unlock PDF'), ('watermark', 'Watermark PDF'), ('page-numbers', 'Page Numbers'), ('organize', 'Organize PDF'), ('crop', 'Crop PDF'), ('html-to-pdf', 'HTML to PDF'), ('pdf-to-html', 'PDF to HTML'), ('markdown-to-pdf', 'Markdown to PDF'), ('pdf-to-markdown', 'PDF to Markdown')], max_length=32),
        ),
    ]
