import {
    FileStack,
    Scissors,
    FileMinus,
    RotateCw,
    Image,
    Images,
    Lock,
    LockOpen,
    Droplet,
    Hash,
    LayoutGrid,
    Crop,
    Code,
    FileCode,
    FileType,
    FileText,
} from "lucide-react";

export type Tool = {
    slug: string;
    name: string;
    description: string;
    icon: any; // Lucide icon component
    color: string; // Tailwind gradient classes
    glow: string; // rgba for glow effects
    available: boolean;
    category: "convert" | "organize" | "secure" | "optimize";
};

export const tools: Tool[] = [
    {
        slug: "merge-pdf",
        name: "Merge PDF",
        description: "Combine multiple PDFs into one document.",
        icon: FileStack,
        color: "from-blue-500 to-blue-600",
        glow: "rgba(59, 130, 246, 0.4)",
        available: true,
        category: "organize",
    },
    {
        slug: "split-pdf",
        name: "Split PDF",
        description: "Separate pages into individual PDFs.",
        icon: Scissors,
        color: "from-violet-500 to-violet-600",
        glow: "rgba(139, 92, 246, 0.4)",
        available: true,
        category: "organize",
    },
    {
        slug: "compress-pdf",
        name: "Compress PDF",
        description: "Reduce file size without losing quality.",
        icon: FileMinus,
        color: "from-emerald-500 to-emerald-600",
        glow: "rgba(16, 185, 129, 0.4)",
        available: true,
        category: "optimize",
    },
    {
        slug: "rotate-pdf",
        name: "Rotate PDF",
        description: "Rotate pages to any orientation.",
        icon: RotateCw,
        color: "from-cyan-500 to-cyan-600",
        glow: "rgba(6, 182, 212, 0.4)",
        available: true,
        category: "organize",
    },
    {
        slug: "pdf-to-jpg",
        name: "PDF to JPG",
        description: "Convert each page into a JPG image.",
        icon: Image,
        color: "from-rose-500 to-rose-600",
        glow: "rgba(244, 63, 94, 0.4)",
        available: true,
        category: "convert",
    },
    {
        slug: "jpg-to-pdf",
        name: "JPG to PDF",
        description: "Combine images into a single PDF.",
        icon: Images,
        color: "from-amber-500 to-amber-600",
        glow: "rgba(245, 158, 11, 0.4)",
        available: true,
        category: "convert",
    },
    {
        slug: "protect-pdf",
        name: "Protect PDF",
        description: "Add password protection to your PDF.",
        icon: Lock,
        color: "from-red-500 to-red-600",
        glow: "rgba(239, 68, 68, 0.4)",
        available: true,
        category: "secure",
    },
    {
        slug: "unlock-pdf",
        name: "Unlock PDF",
        description: "Remove passwords from protected PDFs.",
        icon: LockOpen,
        color: "from-green-500 to-green-600",
        glow: "rgba(34, 197, 94, 0.4)",
        available: true,
        category: "secure",
    },
    {
        slug: "watermark",
        name: "Watermark",
        description: "Stamp text over every page.",
        icon: Droplet,
        color: "from-sky-500 to-sky-600",
        glow: "rgba(14, 165, 233, 0.4)",
        available: true,
        category: "secure",
    },
    {
        slug: "page-numbers",
        name: "Page Numbers",
        description: "Add page numbers with full control.",
        icon: Hash,
        color: "from-indigo-500 to-indigo-600",
        glow: "rgba(99, 102, 241, 0.4)",
        available: true,
        category: "organize",
    },
    {
        slug: "organize-pdf",
        name: "Organize PDF",
        description: "Reorder, delete, or duplicate pages.",
        icon: LayoutGrid,
        color: "from-fuchsia-500 to-fuchsia-600",
        glow: "rgba(217, 70, 239, 0.4)",
        available: true,
        category: "organize",
    },
    {
        slug: "crop-pdf",
        name: "Crop PDF",
        description: "Trim margins or select specific areas.",
        icon: Crop,
        color: "from-orange-500 to-orange-600",
        glow: "rgba(249, 115, 22, 0.4)",
        available: true,
        category: "optimize",
    },
    {
        slug: "html-to-pdf",
        name: "HTML to PDF",
        description: "Convert HTML into a clean PDF.",
        icon: Code,
        color: "from-slate-500 to-slate-600",
        glow: "rgba(100, 116, 139, 0.4)",
        available: true,
        category: "convert",
    },
    {
        slug: "pdf-to-html",
        name: "PDF to HTML",
        description: "Turn PDF pages into a web page.",
        icon: FileCode,
        color: "from-sky-500 to-sky-600",
        glow: "rgba(14, 165, 233, 0.4)",
        available: true,
        category: "convert",
    },
    {
        slug: "markdown-to-pdf",
        name: "Markdown to PDF",
        description: "Render Markdown as a PDF.",
        icon: FileType,
        color: "from-purple-500 to-purple-600",
        glow: "rgba(168, 85, 247, 0.4)",
        available: true,
        category: "convert",
    },
    {
        slug: "pdf-to-markdown",
        name: "PDF to Markdown",
        description: "Extract PDF text as Markdown.",
        icon: FileText,
        color: "from-teal-500 to-teal-600",
        glow: "rgba(20, 184, 166, 0.4)",
        available: true,
        category: "convert",
    },
];

export function getToolBySlug(slug: string): Tool | undefined {
    return tools.find((t) => t.slug === slug);
}

export const categories = [
    { id: "all", name: "All Tools" },
    { id: "convert", name: "Convert" },
    { id: "organize", name: "Organize" },
    { id: "optimize", name: "Optimize" },
    { id: "secure", name: "Secure" },
] as const;